# Stage 1: Build the React app
FROM node:16-alpine AS build

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy all files
COPY . .

# Build the app
RUN npm run build


# Expose port 80
EXPOSE 3000

# Start Nginx server
CMD ["npm",  "start"]
